version: '3'
services:
  csvserver:
    image: infracloudio/csvserver:latest
    env_file:
      - ./csvserver.env
    ports:
      - "9393:9300"
    volumes:
      - ./inputFile:/csvserver/inputdata
